language: node_js
node_js:
  - 10.16.0
before_install:
  - mkdir ./.gcp
  - openssl aes-256-cbc -K $encrypted_9623760e394e_key -iv $encrypted_9623760e394e_iv
    -in gae-svc.json.enc -out .gcp/gae-svc.json -d
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.17.3
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn install
before_deploy:
  - ls
  - yarn run build
jobs:
  include:
    - stage: Test
      script: yarn run coverage
    - stage: Compile
      script: yarn run build
    - stage: Deploy
      script: skip
      name: 'Deploy To Google App Engine'
      deploy:
        provider: gae
        skip_cleanup: true
        keyfile: '.gcp/gae-svc.json'
        project: '$projectId'
        config: app.yaml
stages:
  - Test
  - Compile
  - deploy
