language: node_js
node_js:
  - 10.16.0
before_install:
  - mkdir ./.gcp
  - openssl aes-256-cbc -K $encrypted_9623760e394e_key -iv $encrypted_9623760e394e_iv
    -in gae-svc.json.enc -out .gcp/gae-svc.json -d
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version version-number
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn install
jobs:
  include:
    - stage: Test
      script: yarn test
    - stage: Compile
      script: yarn run build
deploy:
  provider: gae
  keyfile: .gcp/gae-svc.json
  project: cnodejs-graphql-api-apollo
